### ISSUE TITLE
BridgeDb webservice seems old version

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#42]
Compare:

* https://bridgedb.cloud.vhp4safety.nl/config
* http://webservice.bridgedb.org/config

See also https://github.com/VHP4Safety/cloud/issues/40

**Comment by egonw** [comment]
It needed a new BridgeDb Webservice release to create the new Docker, which is now available: https://hub.docker.com/layers/bigcatum/bridgedb/3.0.22-2.1.4/images/sha256-56eb3a2d82ae9244ac79a3992f3750fe71bf8a063b623e91d9516e96e193f199?context=explore

**Comment by ozancinar** [comment]
It's updated.

**Comment by egonw** [comment]
Ah, good detective work! Yeah, that version should not be hardcoded there (cc @marvinm2), I guess. I update the `setup.sh` file and that triggered this Action:

![image](https://github.com/VHP4Safety/cloud/assets/26721/f97734e9-aafa-42b2-a943-f0dc525815aa)

**Comment by ozancinar** [comment]
Just adding @jmillanacosta

**Comment by ozancinar** [comment]
I tried deploying the container yesterday after the new version number had been hardcoded in `setup.sh`. However, it still had the same issue, i.e., the versions were still old under `/config`. 

I redeployed it again today, and it is working now (*see below); [https://bridgedb.cloud.vhp4safety.nl/config](https://bridgedb.cloud.vhp4safety.nl/config) shows this: 
```
java.version	11.0.16
bridgedb.version	3.0.22
webservice.version	2.1.4
```

[https://bridgedb.cloud.vhp4safety.nl/swagger/](https://bridgedb.cloud.vhp4safety.nl/swagger/) also seems to be running. However, if you 'Try it Out' in Identifiers/Get, you'll see that it still leads to a CORS issue. This does not happen if you try the same thing from the IP:port connection, i.e., [http://81.169.225.178:8097/swagger/](http://81.169.225.178:8097/swagger/) does not lead to the CORS issue. 

I redid the nginx and certbot configurations from the beginning. The CORS issue remains, but maybe it is due to the certbot/nginx configuration starting to be in effect after some time. 

* The deployment may be running the latest version due to the hardcode change in the `setup.sh` file made by Egon two days ago. So, the issue with automatically updating the version number in the Github action may still be effective, although it is tackled just now (see the link above).

**Comment by egonw** [comment]
Can it be that you get the CORS because the server is not the domain name but an IP address?

![image](https://github.com/VHP4Safety/cloud/assets/26721/8d0250c8-9090-4936-a461-27c4abc0ce70)
